# Generated by Django 5.0.1 on 2024-01-18 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='название продукта')),
                ('model', models.CharField(max_length=20, verbose_name='модель')),
                ('release_date', models.DateField(verbose_name='дата выхода')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('country', models.CharField(max_length=30, verbose_name='страна')),
                ('city', models.CharField(max_length=30, verbose_name='город')),
                ('street', models.CharField(max_length=30, verbose_name='улица')),
                ('house_number', models.CharField(max_length=30, verbose_name='номер дома')),
                ('category', models.CharField(choices=[('Завод', 'Завод'), ('Розничная сеть', 'Розничная сеть'), ('ИП', 'ИП')], max_length=30, verbose_name='категория')),
                ('debt', models.FloatField(verbose_name='задолженность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.networknode', verbose_name='поставщик')),
                ('products', models.ManyToManyField(to='main.product', verbose_name='продукты')),
            ],
            options={
                'verbose_name': 'звено сети',
                'verbose_name_plural': 'звенья сети',
            },
        ),
    ]
