# Generated by Django 5.0.1 on 2024-01-18 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networknode',
            name='debt',
            field=models.FloatField(blank=True, null=True, verbose_name='задолженность'),
        ),
    ]
